variables:
  # This seems to be necessary in order to be able to use it inside the `ref` statement
  CI_SCRIPTS_BRANCH: dev

ros2 pipeline:
  trigger:
    include:
      - project: 'continuous_integration/ci_scripts'
        ref: $CI_SCRIPTS_BRANCH
        file: '/gitlab-ci-yml/ros2_pipeline_v2.yml'
    strategy: depend
  parallel:
    matrix:
      - ROS_DISTRO: foxy
        CI_IMAGE: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_20.04_ros2:foxy
      - ROS_DISTRO: galactic
        CI_IMAGE: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_20.04_ros2:galactic
      - ROS_DISTRO: humble
        CI_IMAGE: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_22.04_ros2:humble
      - ROS_DISTRO: rolling
        CI_IMAGE: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_22.04_ros2:rolling
